### ISSUE TITLE
[v2.4 updates] 01_PYNQ_Workshop_introduction.pdf

### ISSUE THREAD

**Issue by schelleg** [Xilinx/PYNQ_Workshop#5]
Some update suggestions to the slides:

slide 12 - v2.4 release recommends including HWH files for improved metadata generation.  Tcl is still supported.  DSAs are not supported directly - the HWH file, while included in DSAs, is actually easier to extract directly from a Vivado project.

slide 16 - can update to the IEEE Spectrum 2018 graph.

slide 17 - PyPi packages have gone up to almost ~170K (https://pypi.org/)

slide 21 - add ZCU111, Ultra96

**Comment by cathalmccabe** [comment]
Updated
