### ISSUE TITLE
[v2.4 updates] Session 4 Tcl --> HWH

### ISSUE THREAD

**Issue by schelleg** [Xilinx/PYNQ_Workshop#6]
in v2.4, we report a warning if users are doing a Tcl based overlay vs a HWH overlay.  It is not required for the workshop, but will lead to warnings during Session 4's custom overlay downloads:

![image](https://user-images.githubusercontent.com/12449034/53276055-c21ce000-36ba-11e9-9bab-e59bf9c8021f.png)

**Comment by cathalmccabe** [comment]
Updated
